# Generated by Django 5.2 on 2025-06-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divinationrecord',
            options={'ordering': ['-created_at'], 'verbose_name': '占卜记录', 'verbose_name_plural': '占卜记录'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户档案', 'verbose_name_plural': '用户档案'},
        ),
        migrations.AddField(
            model_name='divinationrecord',
            name='ai_enhanced',
            field=models.BooleanField(default=False, verbose_name='AI增强分析'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_usage_count',
            field=models.IntegerField(default=0, verbose_name='AI使用次数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership',
            field=models.CharField(choices=[('free', '普通用户'), ('vip', '会员用户')], default='free', max_length=10, verbose_name='会员类型'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership_expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='会员到期时间'),
        ),
        migrations.AlterField(
            model_name='divinationrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='divinationrecord',
            name='divination_type',
            field=models.CharField(choices=[('bazi', '八字分析'), ('bazi_marriage', '八字合婚'), ('meihua', '梅花易数'), ('tarot', '塔罗占卜'), ('yijing', '易经卜卦'), ('daily_fortune', '每日运势')], max_length=50, verbose_name='占卜类型'),
        ),
        migrations.AlterField(
            model_name='divinationrecord',
            name='question',
            field=models.TextField(blank=True, verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='divinationrecord',
            name='result',
            field=models.TextField(verbose_name='结果'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出生时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='出生地点'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=10, null=True, verbose_name='性别'),
        ),
        migrations.CreateModel(
            name='DailyFortune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('zodiac', models.CharField(choices=[('rat', '鼠'), ('ox', '牛'), ('tiger', '虎'), ('rabbit', '兔'), ('dragon', '龙'), ('snake', '蛇'), ('horse', '马'), ('goat', '羊'), ('monkey', '猴'), ('rooster', '鸡'), ('dog', '狗'), ('pig', '猪')], max_length=10, verbose_name='生肖')),
                ('overall_fortune', models.IntegerField(default=3, verbose_name='综合运势（1-5星）')),
                ('love_fortune', models.IntegerField(default=3, verbose_name='爱情运势（1-5星）')),
                ('career_fortune', models.IntegerField(default=3, verbose_name='事业运势（1-5星）')),
                ('wealth_fortune', models.IntegerField(default=3, verbose_name='财运（1-5星）')),
                ('health_fortune', models.IntegerField(default=3, verbose_name='健康运势（1-5星）')),
                ('lucky_color', models.CharField(default='红色', max_length=20, verbose_name='幸运颜色')),
                ('lucky_number', models.CharField(default='8', max_length=10, verbose_name='幸运数字')),
                ('description', models.TextField(verbose_name='运势描述')),
                ('ai_enhanced', models.BooleanField(default=False, verbose_name='AI增强分析')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '每日运势',
                'verbose_name_plural': '每日运势',
                'ordering': ['-date', 'zodiac'],
                'unique_together': {('date', 'zodiac')},
            },
        ),
    ]
