# Generated by Django 5.2 on 2025-06-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_smsverification_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsverification',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='请求IP地址'),
        ),
        migrations.AddField(
            model_name='smsverification',
            name='attempt_count',
            field=models.IntegerField(default=0, verbose_name='验证尝试次数'),
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=11, verbose_name='手机号码'),
        ),
    ]
