# Generated by Django 5.2 on 2025-06-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_membershipplan_membershiporder_paymentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divinationrecord',
            name='divination_type',
            field=models.CharField(choices=[('bazi', '八字分析'), ('bazi_marriage', '八字合婚'), ('meihua', '梅花易数'), ('daily_fortune', '每日运势')], max_length=50, verbose_name='占卜类型'),
        ),
    ]
