# Generated by Django 5.2.1 on 2025-05-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseCalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('lunar_year', models.CharField(max_length=20)),
                ('lunar_month', models.CharField(max_length=20)),
                ('lunar_day', models.CharField(max_length=20)),
                ('tiangan', models.CharField(max_length=10)),
                ('dizhi', models.CharField(max_length=10)),
                ('constellation', models.CharField(max_length=20)),
                ('suitable_activities', models.TextField(blank=True)),
                ('avoid_activities', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolarTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
