# Generated by Django 5.2.1 on 2025-05-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaziElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('element_type', models.CharField(choices=[('tiangan', '天干'), ('dizhi', '地支')], max_length=10)),
                ('wuxing', models.CharField(choices=[('jin', '金'), ('mu', '木'), ('shui', '水'), ('huo', '火'), ('tu', '土')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IChingHexagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('chinese_name', models.CharField(max_length=10)),
                ('binary', models.CharField(max_length=6)),
                ('meaning', models.TextField()),
                ('judgment', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('card_number', models.IntegerField()),
                ('suit', models.CharField(choices=[('major', '大阿卡纳'), ('wands', '权杖'), ('cups', '圣杯'), ('swords', '宝剑'), ('pentacles', '金币')], max_length=20)),
                ('upright_meaning', models.TextField()),
                ('reversed_meaning', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tarot_cards/')),
            ],
        ),
    ]
