# Generated by Django 5.2 on 2025-06-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divination', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IChingHexagram',
        ),
        migrations.DeleteModel(
            name='TarotCard',
        ),
    ]
